routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::get('/', function () {
    $data['homepage'] = TRUE;
    return view('frontend.content')->with($data);
});


//Route::get('/shop', function () {
//    $data['homepage'] = FALSE;
//    return view('frontend.shop.index')->with($data);
//});

Route::group(['middleware' => 'checkUserLogin'], function (){
    Route::get('customer/transaction','transactionController@customerTransaction');
    Route::get('customer/profile','customerController@profile');
    Route::post('update/customer/{id}','customerController@update');
    Route::resource('customer','customerController');
    Route::resource('shop','shopController');
    Route::get('shop/category/{id}','shopController@category_detail');
    Route::get('shop/product/detail/{id}','shopController@product_detail');
    Route::get('shop/detail/{id}','shopController@detail');
});

Route::get('login','customerController@login');
//Route::get('customer/logout','customerController@logout');
Route::get('logout', function () {
    try{
        Session::flush();
        return redirect('login')->with('response','Berhasil logout!');
    }
    catch (\Exception $e){
        return redirect('login')->with('response-error',$e->getMessage());
    }
});
Route::post('/customer/check_login','customerController@check_login');



Route::prefix('supplier')->group(function () {
    Route::group(['middleware' => 'checkSupplierLogin'], function () {
        Route::resource('supplier','supplierController');
        Route::resource('product','productController');
        Route::prefix('transaction')->group(function () {
            Route::get('processing/{id}', 'transactionController@processing');
            Route::get('un-process', 'transactionController@transactionUnprocess');
            Route::get('on-process', 'transactionController@transactionInprocess');
        });
    });
    Route::get('/', 'supplierController@login');
    Route::get('profile', 'supplierController@profile');
    Route::get('login', 'supplierController@login');
    Route::get('logout', 'supplierController@logout');
    Route::post('check_login', 'supplierController@check_login');
    Route::get('register', 'supplierController@register');
    //Route::get('product', 'supplierController@register');

});

Route::prefix('admin')->group(function () {
    Route::get('/', 'adminController@login');
    Route::get('suppliers', 'adminController@suppliers');
    Route::get('approve/{id}', 'adminController@approve');
    Route::get('login', 'adminController@login');
    Route::get('logout', 'adminController@logout');
    Route::post('check_login', 'adminController@check_login');

});

resources/views/frontend/alert.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(\Illuminate\Support\Facades\Session::has('response'))
    <div class="alert alert-success">
        {{ \Illuminate\Support\Facades\Session::get('response') }}
    </div>
@endif
@if(\Illuminate\Support\Facades\Session::has('response-error'))
    <div class="alert alert-danger">
        {{ \Illuminate\Support\Facades\Session::get('response-error') }}
    </div>
@endif

resources/views/frontend/base.blade.php
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="zxx">

<head>
   @include('frontend.component.head')
</head>

<body>
@include('frontend.component.header')

@yield('content')
<!--//banner -->

<!-- /newsletter-->
<!--<div class="newsletter_w3layouts_agile">
    <div class="col-sm-6 newsleft">
        <h3>Sign up for Newsletter !</h3>
    </div>
    <div class="col-sm-6 newsright">
        <form action="#" method="post">
            <input type="email" placeholder="Enter your email..." name="email" required="">
            <input type="submit" value="Submit">
        </form>
    </div>

    <div class="clearfix"></div>
</div>-->
<!-- //newsletter-->
<!-- footer -->
@include('frontend.component.footer')
</div>
<!-- //footer -->

@include('frontend.component.script')
</body>

</html>

resources/views/frontend/content.blade.php
@extends('frontend.base')
@section('content')
    <!-- /girds_bottom-->
    <div class="grids_bottom">
        <div class="style-grids">
            <div class="col-md-6 style-grid style-grid-1">
                <img src="/assets/frontend/images/b1.jpg" alt="shoe">
            </div>
        </div>
        <div class="col-md-6 style-grid style-grid-2">
            <div class="style-image-1_info">
                <div class="style-grid-2-text_info">
                    <h3>Best Suppliers</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce pretium vitae urna et placerat. Donec sollicitudin non lectus a efficitur. Etiam in aliquam sem. Nam non magna elit. Fusce ornare ligula fringilla metus tincidunt, et condimentum velit cursus. Sed eleifend lorem in ipsum ornare, at porta ante venenatis. Nulla facilisi. Fusce velit eros, congue quis dolor eu, interdum maximus odio. Mauris eget nisl in diam accumsan sodales. Suspendisse non dui sed eros dignissim egestas. Suspendisse aliquam dui sed luctus finibus.</p>
                    <div class="shop-button">
                        <a href="/shop">Shop Now</a>
                    </div>
                </div>
            </div>
            <div class="style-image-2">
                <img src="/assets/frontend/images/b2.jpg" alt="shoe">
                <div class="style-grid-2-text">
                    <h3>Air force</h3>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
    <!-- //grids_bottom-->
    <!-- /girds_bottom2-->
    <!--<div class="grids_sec_2">
        <div class="style-grids_main">
            <div class="col-md-6 grids_sec_2_left">
                <div class="grid_sec_info">
                    <div class="style-grid-2-text_info">
                        <h3>Sneakers</h3>
                        <p>Itaque earum rerum hic tenetur a sapiente delectus reiciendis maiores alias consequatur.sed quia non numquam eius modi
                            tempora incidunt ut labore .</p>
                        <div class="shop-button">
                            <a href="shop.html">Shop Now</a>
                        </div>
                    </div>
                </div>
                <div class="style-image-2">
                    <img src="/assets/frontend/images/b4.jpg" alt="shoe">
                    <div class="style-grid-2-text">
                        <h3>Air force</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-6 grids_sec_2_left">

                <div class="style-image-2">
                    <img src="/assets/frontend/images/b3.jpg" alt="shoe">
                    <div class="style-grid-2-text">
                        <h3>Air force</h3>
                    </div>
                </div>
                <div class="grid_sec_info last">
                    <div class="style-grid-2-text_info">
                        <h3>Sneakers</h3>
                        <p>Itaque earum rerum hic tenetur a sapiente delectus reiciendis maiores alias consequatur.sed quia non numquam eius modi
                            tempora incidunt ut labore .</p>
                        <div class="shop-button two">
                            <a href="shop.html">Shop Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>-->
    <!-- //grids_bottom2-->
    <!-- /Properties -->
    <div class="mid_slider_w3lsagile">
        <div class="col-md-3 mid_slider_text">
            <h5>More Products</h5>
        </div>
        <div class="col-md-9 mid_slider_info">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                    <li data-target="#myCarousel" data-slide-to="2" class=""></li>
                    <li data-target="#myCarousel" data-slide-to="3" class=""></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g1.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g2.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g3.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g4.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g5.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g6.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g2.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g1.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g1.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g2.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g3.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g4.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g1.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g2.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g3.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                            <div class="col-md-3 col-sm-3 col-xs-3 slidering">
                                <div class="thumbnail"><img src="/assets/frontend/images/g4.jpg" alt="Image" style="max-width:100%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="fa fa-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="fa fa-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                <!-- The Modal -->

            </div>
        </div>

        <div class="clearfix"> </div>
    </div>
@endsection

resources/views/frontend/content2.blade.php
@extends('frontend.base')
@section('content')
    <div class="ads-grid_shop">
        <div class="shop_inner_inf">
            <h3 class="head">Contact Us</h3>
            <p class="head_para">Add Some Description</p>
            <div class="inner_section_w3ls">
                <div class="col-md-6 contact_grid_right">
                    <h6>Please fill this form to contact with us.</h6>
                    <form action="#" method="post">
                        <div class="col-md-6 col-sm-6 contact_left_grid">
                            <input type="text" name="Name" placeholder="Name" required="">
                            <input type="email" name="Email" placeholder="Email" required="">
                        </div>
                        <div class="col-md-6 col-sm-6 contact_left_grid">
                            <input type="text" name="Telephone" placeholder="Telephone" required="">
                            <input type="text" name="Subject" placeholder="Subject" required="">
                        </div>
                        <div class="clearfix"> </div>
                        <textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
                        <input type="submit" value="Submit">
                        <input type="reset" value="Clear">
                    </form>
                </div>
                <div class="col-md-6 contact_grid_right">
                    <h6>Please fill this form to contact with us.</h6>
                    <form action="#" method="post">
                        <div class="col-md-6 col-sm-6 contact_left_grid">
                            <input type="text" name="Name" placeholder="Name" required="">
                            <input type="email" name="Email" placeholder="Email" required="">
                        </div>
                        <div class="col-md-6 col-sm-6 contact_left_grid">
                            <input type="text" name="Telephone" placeholder="Telephone" required="">
                            <input type="text" name="Subject" placeholder="Subject" required="">
                        </div>
                        <div class="clearfix"> </div>
                        <textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
                        <input type="submit" value="Submit">
                        <input type="reset" value="Clear">
                    </form>
                </div>
                <div class="clearfix"> </div>

            </div>

            <div class="clearfix"></div>

        </div>
    </div>
@endsection

resources/views/frontend/login-register.blade.php
@extends('frontend.base')
@section('content')
    <div class="ads-grid_shop">
        <div class="shop_inner_inf">
            <h3 class="head">Login or Register</h3><br>
            <p class="head_para">Sign in to your account or create your account</p>
            <br>
            @include('frontend.alert')
            <div class="inner_section_w3ls">
                <div class="col-md-6 contact_grid_right">
                    <h6>Login</h6>
                    <form action="/customer/check_login" method="post">
                        {{ csrf_field() }}
                        <div class="col-md-12 col-sm-12 contact_left_grid">
                            <input class="form-control" name="username" placeholder="Username...">
                            <br>
                            <input type="password" class="form-control" name="password" placeholder="Password..." required="">
                        </div>
                        <div class="clearfix"> </div>
                        <br>
                        <input type="submit" value="Sign In">
                    </form>
                </div>
                <div class="col-md-6 contact_grid_right">
                    <h6>Register your account here</h6>
                    <form action="{{ route('customer.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="col-md-6 col-sm-6 contact_left_grid">
                            <input class="form-control" name="name" placeholder="Your Name...." >
                            <br>
                            <input class="form-control" name="email" placeholder="Your Email..." >
                        </div>
                        <div class="col-md-6 col-sm-6 contact_left_grid">
                            <input type="password" class="form-control" name="password" placeholder="Password...">
                            <br>
                            <input type="password" class="form-control" name="confirmation_password" placeholder="Password Confirmation..." required="">
                        </div>
                        <div class="clearfix"> </div>
                        <textarea class="form-control" name="address" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="" placeholder="Your address..."></textarea>
                        <input type="submit" value="Sign Up">
                        <input type="reset" value="Clear">
                    </form>
                </div>
                <div class="clearfix"> </div>

            </div>

            <div class="clearfix"></div>

        </div>
    </div>

    <script>
        $( document ).ready(function() {
            $('.pass').on('click', function () {
                $(this).attr('type', 'password');
            });
        });
    </script>
@endsection