routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::get('/', function () {
    $data['homepage'] = TRUE;
    return view('frontend.content')->with($data);
});


//Route::get('/shop', function () {
//    $data['homepage'] = FALSE;
//    return view('frontend.shop.index')->with($data);
//});

Route::group(['middleware' => 'checkUserLogin'], function (){
    Route::get('customer/transaction','transactionController@customerTransaction');
    Route::get('customer/profile','customerController@profile');
    Route::post('update/customer/{id}','customerController@update');
    Route::resource('customer','customerController');
    Route::resource('shop','shopController');
    Route::get('shop/category/{id}','shopController@category_detail');
    Route::get('shop/product/detail/{id}','shopController@product_detail');
    Route::get('shop/detail/{id}','shopController@detail');
});

Route::get('login','customerController@login');
//Route::get('customer/logout','customerController@logout');
Route::get('logout', function () {
    try{
        Session::flush();
        return redirect('login')->with('response','Berhasil logout!');
    }
    catch (\Exception $e){
        return redirect('login')->with('response-error',$e->getMessage());
    }
});
Route::post('/customer/check_login','customerController@check_login');



Route::prefix('supplier')->group(function () {
    Route::group(['middleware' => 'checkSupplierLogin'], function () {
        Route::resource('supplier','supplierController');
        Route::resource('product','productController');
        Route::prefix('transaction')->group(function () {
            Route::get('processing/{id}', 'transactionController@processing');
            Route::get('un-process', 'transactionController@transactionUnprocess');
            Route::get('on-process', 'transactionController@transactionInprocess');
        });
    });
    Route::get('/', 'supplierController@login');
    Route::get('profile', 'supplierController@profile');
    Route::get('login', 'supplierController@login');
    Route::get('logout', 'supplierController@logout');
    Route::post('check_login', 'supplierController@check_login');
    Route::get('register', 'supplierController@register');
    //Route::get('product', 'supplierController@register');

});

Route::prefix('admin')->group(function () {
    Route::get('/', 'adminController@login');
    Route::get('suppliers', 'adminController@suppliers');
    Route::get('approve/{id}', 'adminController@approve');
    Route::get('login', 'adminController@login');
    Route::get('logout', 'adminController@logout');
    Route::post('check_login', 'adminController@check_login');

});

app/Http/Controllers/shopController.php
<?php

namespace App\Http\Controllers;

use App\productModel;
use App\productTypeModel;
use App\supplierModel;
use App\supplierTypeModel;
use App\transactionModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class shopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $supplierType = supplierTypeModel::all();
            $data['homepage'] = FALSE;
            $data['supplier_type'] = $supplierType;
            return view('frontend.shop.index')->with($data);

        }
        catch (\Exception $e){
            return view('frontend.shop.index')->with('response-error', $e->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $this->validate($request, [
                'notes' => 'required',
            ]);

            $data = new transactionModel();
            $data->transaction_code = time();
            $data->customer_id = Session::get('customer_id');
            $data->product_id = decrypt($request->product_id);
            $data->notes = $request->notes;
            $data->count = $request->quantity;
            $data->supplier_id = decrypt($request->supplier_id);
            $data->save();
            return redirect()->back()->with('response', 'Successful order the product!!');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try{
            $supplier = supplierModel::where('supplier_type',decrypt($id))->get();
            $data['homepage'] = FALSE;
            $data['supplier'] = $supplier;
            return view('frontend.shop.supplier')->with($data);

        }
        catch (\Exception $e){
            return view('frontend.shop.supplier')->with('response-error', $e->getMessage());
        }
    }

    public function detail($id)
    {
        try{
            $supplier = supplierModel::where('id',decrypt($id))->first();
            $product_type = productTypeModel::where('supplier_type',$supplier->supplier_type)->get();
            $product = productModel::where('supplier_id',$supplier->id)->get();
            $data['homepage'] = FALSE;
            $data['supplier'] = $supplier;
            $data['product'] = $product;
            $data['product_type'] = $product_type;
            return view('frontend.shop.supplier.detail')->with($data);

        }
        catch (\Exception $e){
            return view('frontend.shop.supplier.detail')->with('response-error', $e->getMessage());
        }
    }

    public function category_detail($id)
    {
        try{
            $product = productModel::where('product_type',decrypt($id))->get();
            //$supplier = supplierModel::where('id',$product->supplier_id)->get();
            $category = productTypeModel::where('id',decrypt($id))->first();
            $data['homepage'] = FALSE;
            $data['product'] = $product;
            $data['category'] = $category->name;
            return view('frontend.shop.supplier.product_by_category')->with($data);
        }
        catch (\Exception $e){
            return view('frontend.shop.supplier.product_by_category')->with('response-error', $e->getMessage());
        }
    }

    public function product_detail($id)
    {
        try{
            $product = productModel::where('id',decrypt($id))->get();
            $data['homepage'] = FALSE;
            $data['product'] = $product;
            return view('frontend.shop.supplier.detail_product')->with($data);
        }
        catch (\Exception $e){
            return view('frontend.shop.supplier.detail_product')->with('response-error', $e->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/frontend/shop/index.blade.php
@extends('frontend.base')
@section('content')
    <div class="ads-grid_shop">
        <div class="shop_inner_inf">
            @include('frontend.alert')
            <!-- tittle heading -->
            <!-- //tittle heading -->
            <!-- product left -->
            {{--<div class="side-bar col-md-3">--}}
                {{--<!-- deals -->--}}
                {{--<div class="deal-leftmk left-side">--}}
                    {{--<h3 class="agileits-sear-head">Categr</h3>--}}
                    {{--<div class="special-sec1">--}}
                        {{--<div class="col-xs-8 img-deal1">--}}
                            {{--<h3>Shuberry Heels</h3>--}}
                            {{--<a href="single.html">$180.00</a>--}}
                        {{--</div>--}}
                        {{--<div class="clearfix"></div>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<!-- //deals -->--}}

            {{--</div>--}}
            <!-- //product left -->
            <!-- product right -->
            <div class="left-ads-display col-md-12">
                <div class="wrapper_top_shop">
                    <div class="col-md-6 shop_left">
                        <img src="/assets/frontend/images/banner3.jpg" alt="">
                        <h6>40% off</h6>
                    </div>
                    <div class="col-md-6 shop_right">
                        <img src="/assets/frontend/images/banner2.jpg" alt="">
                        <h6>50% off</h6>
                    </div>
                    <div class="clearfix"></div>
                    <!-- product-sec1 -->
                    <div class="product-sec1">
                        <!--/mens-->
                        @foreach($supplier_type as $item)
                        <div class="col-md-4 product-men">
                            <div class="product-shoe-info shoe">
                                <div class="men-pro-item">
                                    <div class="men-thumb-item">
                                        <img src="/assets/frontend/images/white.jpg" style="height: 120px; width: 120px;" alt="">
                                        <div class="men-cart-pro">
                                            <div class="inner-men-cart-pro">
                                                <a href="{{ route('shop.show',encrypt($item->id)) }}" class="link-product-add-cart">Quick View</a>
                                            </div>
                                        </div>
                                        {{--<span class="product-new-top">New</span>--}}
                                    </div>
                                    <div class="item-info-product">
                                        <h4>
                                            <a href="{{ route('shop.show',encrypt($item->id)) }}">{{ $item->name }}</a>
                                        </h4>
                                        <div class="info-product-price">
                                            <div class="grid_meta">
                                                <div class="product_price">
                                                    <div class="grid-price ">
                                                        <span class="money ">Total Suppliers : {{ count(\App\supplierModel::where('supplier_type',$item->id)->get()) }}</span>
                                                        <br>
                                                        @php $count = 0 @endphp
                                                        @foreach( \App\productTypeModel::where('supplier_type',$item->id)->get() as $productType)
                                                            @php
                                                                $data = \App\productModel::where('product_type', $productType->id)->count();
                                                                if($data){
                                                                    $count += $data;
                                                                }
                                                            @endphp
                                                        @endforeach
                                                        <span class="money ">Total Products &nbsp;: {{ $count }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            {{--<div class="shoe single-item hvr-outline-out">--}}
                                                {{--<form action="#" method="post">--}}
                                                    {{--<input type="hidden" name="cmd" value="_cart">--}}
                                                    {{--<input type="hidden" name="add" value="1">--}}
                                                    {{--<input type="hidden" name="shoe_item" value="Bella Toes">--}}
                                                    {{--<input type="hidden" name="amount" value="675.00">--}}
                                                    {{--<button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>--}}

                                                    {{--<a href="#" data-toggle="modal" data-target="#myModal1"></a>--}}
                                                {{--</form>--}}

                                            {{--</div>--}}
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                        <div class="clearfix"></div>
                    </div>

                    {{--<!-- //product-sec1 -->--}}
                    {{--<div class="col-md-6 shop_left shp">--}}
                        {{--<img src="/assets/frontend/images/banner4.jpg" alt="">--}}
                        {{--<h6>21% off</h6>--}}
                    {{--</div>--}}
                    {{--<div class="col-md-6 shop_right shp">--}}
                        {{--<img src="/assets/frontend/images/banner1.jpg" alt="">--}}
                        {{--<h6>31% off</h6>--}}
                    {{--</div>--}}
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection

resources/views/frontend/shop/supplier.blade.php
@extends('frontend.base')
@section('content')
    <div class="ads-grid_shop">
        <div class="shop_inner_inf">
            @include('frontend.alert')
            <!-- tittle heading -->
            <!-- //tittle heading -->
            <!-- product left -->
            {{--<div class="side-bar col-md-3">--}}
                {{--<!-- deals -->--}}
                {{--<div class="deal-leftmk left-side">--}}
                    {{--<h3 class="agileits-sear-head">Categr</h3>--}}
                    {{--<div class="special-sec1">--}}
                        {{--<div class="col-xs-8 img-deal1">--}}
                            {{--<h3>Shuberry Heels</h3>--}}
                            {{--<a href="single.html">$180.00</a>--}}
                        {{--</div>--}}
                        {{--<div class="clearfix"></div>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<!-- //deals -->--}}

            {{--</div>--}}
            <!-- //product left -->
            <!-- product right -->
            <div class="left-ads-display col-md-12">
                <div class="wrapper_top_shop">
                    <div class="col-md-6 shop_left">
                        <img src="/assets/frontend/images/banner3.jpg" alt="">
                        <h6>40% off</h6>
                    </div>
                    <div class="col-md-6 shop_right">
                        <img src="/assets/frontend/images/banner2.jpg" alt="">
                        <h6>50% off</h6>
                    </div>
                    <div class="clearfix"></div>
                    <!-- product-sec1 -->
                    <div class="product-sec1">
                        <!--/mens-->
                        @foreach($supplier as $item)
                        <div class="col-md-4 product-men">
                            <div class="product-shoe-info shoe">
                                <div class="men-pro-item">
                                    <div class="men-thumb-item">
                                        <img src="/assets/frontend/images/white.jpg" style="height: 120px; width: 120px;" alt="">
                                        <div class="men-cart-pro">
                                            <div class="inner-men-cart-pro">
                                                <a href="/shop/detail/{{ encrypt($item->id) }}" class="link-product-add-cart">Quick View</a>
                                            </div>
                                        </div>
                                        {{--<span class="product-new-top">New</span>--}}
                                    </div>
                                    <div class="item-info-product">
                                        <h4>
                                            <a href="/shop/detail/{{ encrypt($item->id) }}">{{ $item->name }}</a>
                                        </h4>
                                        <div class="info-product-price">
                                            <div class="grid_meta">
                                                <div class="product_price">
                                                    <div class="grid-price ">
                                                        <span class="money ">Total Product : {{ count(\App\productModel::where('supplier_id',$item->id)->count()) }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            {{--<div class="shoe single-item hvr-outline-out">--}}
                                                {{--<form action="#" method="post">--}}
                                                    {{--<input type="hidden" name="cmd" value="_cart">--}}
                                                    {{--<input type="hidden" name="add" value="1">--}}
                                                    {{--<input type="hidden" name="shoe_item" value="Bella Toes">--}}
                                                    {{--<input type="hidden" name="amount" value="675.00">--}}
                                                    {{--<button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>--}}

                                                    {{--<a href="#" data-toggle="modal" data-target="#myModal1"></a>--}}
                                                {{--</form>--}}

                                            {{--</div>--}}
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                        <div class="clearfix"></div>
                    </div>

                    {{--<!-- //product-sec1 -->--}}
                    {{--<div class="col-md-6 shop_left shp">--}}
                        {{--<img src="/assets/frontend/images/banner4.jpg" alt="">--}}
                        {{--<h6>21% off</h6>--}}
                    {{--</div>--}}
                    {{--<div class="col-md-6 shop_right shp">--}}
                        {{--<img src="/assets/frontend/images/banner1.jpg" alt="">--}}
                        {{--<h6>31% off</h6>--}}
                    {{--</div>--}}
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection