routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::get('/', function () {
    $data['homepage'] = TRUE;
    return view('frontend.content')->with($data);
});


//Route::get('/shop', function () {
//    $data['homepage'] = FALSE;
//    return view('frontend.shop.index')->with($data);
//});

Route::group(['middleware' => 'checkUserLogin'], function (){
    Route::get('customer/transaction','transactionController@customerTransaction');
    Route::get('customer/profile','customerController@profile');
    Route::post('update/customer/{id}','customerController@update');
    Route::resource('customer','customerController');
    Route::resource('shop','shopController');
    Route::get('shop/category/{id}','shopController@category_detail');
    Route::get('shop/product/detail/{id}','shopController@product_detail');
    Route::get('shop/detail/{id}','shopController@detail');
});

Route::get('login','customerController@login');
//Route::get('customer/logout','customerController@logout');
Route::get('logout', function () {
    try{
        Session::flush();
        return redirect('login')->with('response','Berhasil logout!');
    }
    catch (\Exception $e){
        return redirect('login')->with('response-error',$e->getMessage());
    }
});
Route::post('/customer/check_login','customerController@check_login');



Route::prefix('supplier')->group(function () {
    Route::group(['middleware' => 'checkSupplierLogin'], function () {
        Route::resource('supplier','supplierController');
        Route::resource('product','productController');
        Route::prefix('transaction')->group(function () {
            Route::get('processing/{id}', 'transactionController@processing');
            Route::get('un-process', 'transactionController@transactionUnprocess');
            Route::get('on-process', 'transactionController@transactionInprocess');
        });
    });
    Route::get('/', 'supplierController@login');
    Route::get('profile', 'supplierController@profile');
    Route::get('login', 'supplierController@login');
    Route::get('logout', 'supplierController@logout');
    Route::post('check_login', 'supplierController@check_login');
    Route::get('register', 'supplierController@register');
    //Route::get('product', 'supplierController@register');

});

Route::prefix('admin')->group(function () {
    Route::get('/', 'adminController@login');
    Route::get('suppliers', 'adminController@suppliers');
    Route::get('approve/{id}', 'adminController@approve');
    Route::get('login', 'adminController@login');
    Route::get('logout', 'adminController@logout');
    Route::post('check_login', 'adminController@check_login');

});

app/Http/Controllers/shopController.php
<?php

namespace App\Http\Controllers;

use App\productModel;
use App\productTypeModel;
use App\supplierModel;
use App\supplierTypeModel;
use App\transactionModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class shopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $supplierType = supplierTypeModel::all();
            $data['homepage'] = FALSE;
            $data['supplier_type'] = $supplierType;
            return view('frontend.shop.index')->with($data);

        }
        catch (\Exception $e){
            return view('frontend.shop.index')->with('response-error', $e->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $this->validate($request, [
                'notes' => 'required',
            ]);

            $data = new transactionModel();
            $data->transaction_code = time();
            $data->customer_id = Session::get('customer_id');
            $data->product_id = decrypt($request->product_id);
            $data->notes = $request->notes;
            $data->count = $request->quantity;
            $data->supplier_id = decrypt($request->supplier_id);
            $data->save();
            return redirect()->back()->with('response', 'Successful order the product!!');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try{
            $supplier = supplierModel::where('supplier_type',decrypt($id))->get();
            $data['homepage'] = FALSE;
            $data['supplier'] = $supplier;
            return view('frontend.shop.supplier')->with($data);

        }
        catch (\Exception $e){
            return view('frontend.shop.supplier')->with('response-error', $e->getMessage());
        }
    }

    public function detail($id)
    {
        try{
            $supplier = supplierModel::where('id',decrypt($id))->first();
            $product_type = productTypeModel::where('supplier_type',$supplier->supplier_type)->get();
            $product = productModel::where('supplier_id',$supplier->id)->get();
            $data['homepage'] = FALSE;
            $data['supplier'] = $supplier;
            $data['product'] = $product;
            $data['product_type'] = $product_type;
            return view('frontend.shop.supplier.detail')->with($data);

        }
        catch (\Exception $e){
            return view('frontend.shop.supplier.detail')->with('response-error', $e->getMessage());
        }
    }

    public function category_detail($id)
    {
        try{
            $product = productModel::where('product_type',decrypt($id))->get();
            //$supplier = supplierModel::where('id',$product->supplier_id)->get();
            $category = productTypeModel::where('id',decrypt($id))->first();
            $data['homepage'] = FALSE;
            $data['product'] = $product;
            $data['category'] = $category->name;
            return view('frontend.shop.supplier.product_by_category')->with($data);
        }
        catch (\Exception $e){
            return view('frontend.shop.supplier.product_by_category')->with('response-error', $e->getMessage());
        }
    }

    public function product_detail($id)
    {
        try{
            $product = productModel::where('id',decrypt($id))->get();
            $data['homepage'] = FALSE;
            $data['product'] = $product;
            return view('frontend.shop.supplier.detail_product')->with($data);
        }
        catch (\Exception $e){
            return view('frontend.shop.supplier.detail_product')->with('response-error', $e->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/supplierController.php
<?php

namespace App\Http\Controllers;

use App\supplierModel;
use App\supplierTypeModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class supplierController extends Controller
{
    public function __construct()
    {
        $this->email = new emailController();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        try{
            $this->validate($request, [
                'name' => 'required|min:6',
                'address' => 'required|min:6',
                'email' => 'required|unique:suppliers|min:6|email',
                'password' => 'required|min:6',
                'confirmation_password' => 'required|same:password',
            ]);

            $data = new supplierModel();
            $data->name = $request->name;
            $data->address = $request->address;
            $data->email = $request->email;
            $data->password = bcrypt($request->password);
            $data->supplier_type = $request->supplier_type;
            $data->slogan = $request->slogan;
            $code = time();
            $data->supplier_code = $code;
            $data->save();
            //$this->email->registration($request->name,$request->email,$code);
            return redirect()->back()->with('response', 'Register berhasil! silahkan gunakan '. $code .' untuk login sebagai username, dan password yang sudah anda masukkan! Jika anda lupa anda dapat mengeceknya di email anda!');

        }
        catch (\Exception $e){
            return redirect('supplier-register')->with('response-error', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function profile()
    {
        try{
            $supplier = supplierModel::where('id',Session::get('supplier_id'))->first();
            $type = supplierTypeModel::all();
            $data['supplier'] = $supplier;
            $data['type'] = $type;
            //$this->email->registration($request->name,$request->email,$code);
            return view('backends.supplier.edit_profile')->with($data);

        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $this->validate($request, [
                'confirmation_password' => 'same:password',
            ]);

            $data = supplierModel::where('id',decrypt($id))->first();
            $data->name = $request->name;
            $data->slogan = $request->slogan;
            $data->email = $request->email;
            if(empty($request->password)){
                $data->password = $data->password;
            }
            else{
                $data->password = bcrypt($request->password);
            }
            $data->address = $request->address;
            $data->supplier_type = $data->supplier_type;
            $data->save();
            return redirect('supplier/product')->with('response','Sucessfull update data!');

        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function login(){
        try{
            return view('backends.login');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }

    public function logout(){
        try{
            Session::flush();
            return redirect('supplier/login')->with('response','Berhasil logout!');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }


    public function check_login(Request $request){
        try{
            $data = supplierModel::where('supplier_code',$request->code)->where('status',1)->first();

            if($data){
                if(Hash::check($request->password,$data->password)){
                    Session::put('supplier_id',$data->id);
                    Session::put('supplier_name',$data->name);
                    Session::put('supplier_email',$data->email);
                    Session::put('supplier_isLogin',true);
                    return redirect()->route('product.index');
                }
                else{
                    return redirect()->back()->with('response-error', 'Wrong credientials username or password!');
                }
            }
            else{
                return redirect()->back()->with('response-error', 'We can`t found this account');
            }
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }


    public function register(){
        try{
            $data['supplier_type'] = supplierTypeModel::all();
            return view('backends.register')->with($data);
        }
        catch (\Exception $e){
            return redirect('supplier-register')->with('response-error', $e->getMessage());
        }

    }
}

resources/views/frontend/shop/supplier/detail.blade.php
@extends('frontend.base')
@section('content')
    <div class="ads-grid_shop">
    <div class="shop_inner_inf">
        <div class="col-md-8 single-right-left simpleCart_shelfItem">
            <h3> {{ $supplier->name }} </h3>
            <hr>
            <div class="alert alert-info">
                <p style="font-size: 12pt">Hi, {{ \Illuminate\Support\Facades\Session::get('customer_name') }}, welcome to {{ $supplier->name }}</p>
                <p style="font-size: 12pt"><b>{{ $supplier->slogan }}</b></p>
                <hr>
                <p style="font-size: 12pt">Address : {{ $supplier->address }}</p>
            </div>




        </div>
        <div class="clearfix"> </div>
        <!--/tabs-->

        <!--//tabs-->
        <div class="new_arrivals">
            <h3>Category</h3>
            <!-- /womens -->
            @foreach($product_type as $value)
                <div class="col-md-3 product-men women_two">
                    <div class="product-shoe-info shoe">
                        <div class="men-pro-item">
                            <div class="men-thumb-item">
                                <img src="/assets/frontend/images/white.jpg" style="height: 120px; width: 120px;" alt="">
                                <div class="men-cart-pro">
                                    <div class="inner-men-cart-pro">
                                        <a href="/shop/category/{{ encrypt($value->id) }}" class="link-product-add-cart">Quick View</a>
                                    </div>
                                </div>
                                {{--<span class="product-new-top">New</span>--}}
                            </div>
                            <div class="item-info-product">
                                <h4>
                                    <a href="/shop/category/{{ encrypt($value->id) }}">{{ $value->name }}</a>
                                </h4>
                                <div class="info-product-price">
                                    <div class="grid_meta">
                                        <div class="product_price">
                                            <div class="grid-price ">
                                                {{--<span class="money ">Rp. {{ $value->price }}</span>--}}
                                            </div>
                                        </div>
                                        {{--<ul class="stars">--}}
                                        {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                        {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                        {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                        {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                        {{--<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>--}}
                                        {{--</ul>--}}
                                    </div>
                                    {{--<div class="shoe single-item hvr-outline-out">--}}
                                    {{--<form action="#" method="post">--}}
                                    {{--<input type="hidden" name="cmd" value="_cart">--}}
                                    {{--<input type="hidden" name="add" value="1">--}}
                                    {{--<input type="hidden" name="shoe_item" value="Shuberry Heels">--}}
                                    {{--<input type="hidden" name="amount" value="575.00">--}}
                                    {{--<button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>--}}

                                    {{--<a href="#" data-toggle="modal" data-target="#myModal1"></a>--}}
                                    {{--</form>--}}

                                    {{--</div>--}}
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
        @endforeach
        <!-- //womens -->
            <div class="clearfix"></div>
        </div>
        <!-- /new_arrivals -->

        <!--//new_arrivals-->


    </div>
    </div>
@endsection

resources/views/frontend/shop/supplier/detail_product.blade.php
@extends('frontend.base')
@section('content')
    <div class="ads-grid_shop">
        <div class="shop_inner_inf">
            <div class="col-md-8 single-right-left simpleCart_shelfItem">
                @foreach($product as $value)
                <h3> {{ $value->name }}</h3>
                <hr>
                <p style="font-size: 12pt"> price: Rp. {{$value->price}}</p>
                <div class="occasion-cart">
                    <div class="shoe single-item single_page_b">
                        @include('frontend.alert')
                        <form action="{{ route('shop.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="description">
                                <h5>Notes to Seller</h5>
                                <input type="hidden" name="product_id" value="{{ encrypt($value->id) }}">
                                <input type="hidden" name="supplier_id" value="{{ encrypt($value->supplier_id) }}">
                                <input type="text" name="notes" value="Enter pincode" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter pincode';}" required="">
                            </div>
                            <div class="color-quality">
                                <div class="color-quality-right">
                                    <h5>Quantity :</h5>
                                    <select id="country1" name="quantity" onchange="change_country(this.value)" class="frm-field required sect">
                                        @for($i =1; $i < 100; $i++)
                                            <option value="{{ $i}}">{{ $i }}</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                            <br>
                            <input type="submit" name="submit" value="Order" class="button add">

                            <a href="#" data-toggle="modal" data-target="#myModal1"></a>
                        </form>

                    </div>

                </div>
            @endforeach
            </div>
            <div class="clearfix"> </div>
            <!--/tabs-->

            <!--//tabs-->
            <!-- /new_arrivals -->
            <div class="new_arrivals">
                <h3>Other Products</h3>
                <!-- /womens -->
                @foreach($product as $value)
                @foreach(\App\productModel::where('id','!=',$value->id)->where('supplier_id',$value->supplier_id)->get() as $item)
                    <div class="col-md-3 product-men women_two">
                        <div class="product-shoe-info shoe">
                            <div class="men-pro-item">
                                <div class="men-thumb-item">
                                    <img src="/assets/frontend/images/white.jpg" style="height: 120px; width: 120px;" alt="">
                                    <div class="men-cart-pro">
                                        <div class="inner-men-cart-pro">
                                            <a href="/shop/product/detail/{{ encrypt($item->id) }}" class="link-product-add-cart">Quick View</a>
                                        </div>
                                    </div>
                                    {{--<span class="product-new-top">New</span>--}}
                                </div>
                                <div class="item-info-product">
                                    <h4>
                                        <a href="/shop/product/detail/{{ encrypt($item->id) }}"> {{$item->name }}</a>
                                    </h4>
                                    <div class="info-product-price">
                                        <div class="grid_meta">
                                            <div class="product_price">
                                                <div class="grid-price ">
                                                    <span class="money ">Rp. {{ $item->price }}</span>
                                                </div>
                                            </div>
                                            {{--<ul class="stars">--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>--}}
                                            {{--</ul>--}}
                                        </div>
                                        {{--<div class="shoe single-item hvr-outline-out">--}}
                                        {{--<form action="#" method="post">--}}
                                        {{--<input type="hidden" name="cmd" value="_cart">--}}
                                        {{--<input type="hidden" name="add" value="1">--}}
                                        {{--<input type="hidden" name="shoe_item" value="Shuberry Heels">--}}
                                        {{--<input type="hidden" name="amount" value="575.00">--}}
                                        {{--<button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>--}}

                                        {{--<a href="#" data-toggle="modal" data-target="#myModal1"></a>--}}
                                        {{--</form>--}}

                                        {{--</div>--}}
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
            @endforeach
            @endforeach
            <!-- //womens -->
                <div class="clearfix"></div>
            </div>
            <!--//new_arrivals-->


        </div>
    </div>
@endsection

resources/views/frontend/shop/supplier/product_by_category.blade.php
@extends('frontend.base')
@section('content')
    <div class="ads-grid_shop">
        <div class="shop_inner_inf">
            <div class="clearfix"> </div>
            <!--/tabs-->

            <!--//tabs-->
            <!-- /new_arrivals -->
            <div class="new_arrivals">
                @foreach($product as $value)
                    @php $supplier = \App\supplierModel::where('id',$value->supplier_id)->first() @endphp
                @endforeach
                <h3> {{ $supplier->name }} Products by Category {{ $category }}</h3>
                <!-- /womens -->
                @foreach($product as $value)
                    <div class="col-md-3 product-men women_two">
                        <div class="product-shoe-info shoe">
                            <div class="men-pro-item">
                                <div class="men-thumb-item">
                                    <img src="/assets/frontend/images/white.jpg" style="height: 120px; width: 120px;" alt="">
                                    <div class="men-cart-pro">
                                        <div class="inner-men-cart-pro">
                                            <a href="/shop/product/detail/{{ encrypt($value->id) }}" class="link-product-add-cart">Quick View</a>
                                        </div>
                                    </div>
                                    {{--<span class="product-new-top">New</span>--}}
                                </div>
                                <div class="item-info-product">
                                    <h4>
                                        <a href="/shop/product/detail/{{ encrypt($value->id) }}"> {{$value->name}} </a>
                                    </h4>
                                    <div class="info-product-price">
                                        <div class="grid_meta">
                                            <div class="product_price">
                                                <div class="grid-price ">
                                                    <span class="money ">Rp. {{ $value->price }}</span>
                                                </div>
                                            </div>
                                            {{--<ul class="stars">--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>--}}
                                            {{--<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>--}}
                                            {{--</ul>--}}
                                        </div>
                                        {{--<div class="shoe single-item hvr-outline-out">--}}
                                        {{--<form action="#" method="post">--}}
                                        {{--<input type="hidden" name="cmd" value="_cart">--}}
                                        {{--<input type="hidden" name="add" value="1">--}}
                                        {{--<input type="hidden" name="shoe_item" value="Shuberry Heels">--}}
                                        {{--<input type="hidden" name="amount" value="575.00">--}}
                                        {{--<button type="submit" class="shoe-cart pshoe-cart"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>--}}

                                        {{--<a href="#" data-toggle="modal" data-target="#myModal1"></a>--}}
                                        {{--</form>--}}

                                        {{--</div>--}}
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
            @endforeach
            <!-- //womens -->
                <div class="clearfix"></div>
            </div>
            <!--//new_arrivals-->


        </div>
    </div>
@endsection