routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::get('/', function () {
    $data['homepage'] = TRUE;
    return view('frontend.content')->with($data);
});


//Route::get('/shop', function () {
//    $data['homepage'] = FALSE;
//    return view('frontend.shop.index')->with($data);
//});

Route::group(['middleware' => 'checkUserLogin'], function (){
    Route::get('customer/transaction','transactionController@customerTransaction');
    Route::get('customer/profile','customerController@profile');
    Route::post('update/customer/{id}','customerController@update');
    Route::resource('customer','customerController');
    Route::resource('shop','shopController');
    Route::get('shop/category/{id}','shopController@category_detail');
    Route::get('shop/product/detail/{id}','shopController@product_detail');
    Route::get('shop/detail/{id}','shopController@detail');
});

Route::get('login','customerController@login');
//Route::get('customer/logout','customerController@logout');
Route::get('logout', function () {
    try{
        Session::flush();
        return redirect('login')->with('response','Berhasil logout!');
    }
    catch (\Exception $e){
        return redirect('login')->with('response-error',$e->getMessage());
    }
});
Route::post('/customer/check_login','customerController@check_login');



Route::prefix('supplier')->group(function () {
    Route::group(['middleware' => 'checkSupplierLogin'], function () {
        Route::resource('supplier','supplierController');
        Route::resource('product','productController');
        Route::prefix('transaction')->group(function () {
            Route::get('processing/{id}', 'transactionController@processing');
            Route::get('un-process', 'transactionController@transactionUnprocess');
            Route::get('on-process', 'transactionController@transactionInprocess');
        });
    });
    Route::get('/', 'supplierController@login');
    Route::get('profile', 'supplierController@profile');
    Route::get('login', 'supplierController@login');
    Route::get('logout', 'supplierController@logout');
    Route::post('check_login', 'supplierController@check_login');
    Route::get('register', 'supplierController@register');
    //Route::get('product', 'supplierController@register');

});

Route::prefix('admin')->group(function () {
    Route::get('/', 'adminController@login');
    Route::get('suppliers', 'adminController@suppliers');
    Route::get('approve/{id}', 'adminController@approve');
    Route::get('login', 'adminController@login');
    Route::get('logout', 'adminController@logout');
    Route::post('check_login', 'adminController@check_login');

});

app/Http/Controllers/productController.php
<?php

namespace App\Http\Controllers;

use App\productModel;
use App\productTypeModel;
use App\supplierModel;
use App\supplierTypeModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class productController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $supplier = supplierModel::where('id',Session::get('supplier_id'))->first();
            $data['product_type'] = productTypeModel::where('supplier_type', $supplier->supplier_type)->get();
            return view('backends.supplier.product.type')->with($data);
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }

    public function type()
    {
        try{
            $supplier = supplierModel::where('id',Session::get('supplier_id'))->first();
            $data['product_type'] = productTypeModel::where('supplier_type', $supplier->supplier_type)->get();
            return view('backends.supplier.product.type')->with($data);
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try{
            $supplier = supplierModel::where('id',Session::get('supplier_id'))->first();
            $data['product_type'] = productTypeModel::where('supplier_type',$supplier->supplier_type)->get();
            return view('backends.supplier.product.add')->with($data);
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $this->validate($request, [
                'name' => 'required|min:6',
                'product_code' => 'required|unique:products|min:6',
                'price' => 'required|min:6|integer',
            ]);

            $data = new productModel();
            $data->name = $request->name;
            $data->product_type = $request->product_type;
            $data->product_code = $request->product_code;
            $data->price = $request->price;
            $data->supplier_id = Session::get('supplier_id');
            $data->save();
            return redirect()->route('product.show',encrypt($request->product_type))->with('response', 'Berhasil Menambahkan Data!');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try{
            $ids = decrypt($id);
            $data['product'] = productModel::where('supplier_id',Session::get('supplier_id'))->where('product_type',$ids)->get();
            return view('backends.supplier.product.show')->with($data);
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $ids = decrypt($id);
            $supplier = supplierModel::where('id',Session::get('supplier_id'))->first();
            $data['product'] = productModel::where('id',$ids)->first();
            $data['product_type'] = productTypeModel::where('supplier_type',$supplier->supplier_type)->get();
            return view('backends.supplier.product.edit')->with($data);
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $this->validate($request, [
                'name' => 'required|min:6',
                'price' => 'required|min:6|integer',
            ]);

            $data = productModel::where('id',decrypt($id))->first();
            $data->name = $request->name;
            $ids = $data->product_type;
            $data->product_type = $data->product_type;
            $data->product_code = $data->product_code;
            $data->price = $request->price;
            $data->supplier_id = Session::get('supplier_id');
            $data->status = $request->product_status;
            $data->save();
            return redirect()->route('product.show',encrypt($ids))->with('response', 'Berhasil Mengubah Data!');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $data = productModel::where('id',decrypt($id))->first();
            $data->delete();
            return redirect()->route('product.index')->with('response', 'Success Delete Data!');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }
}

app/Http/Controllers/supplierController.php
<?php

namespace App\Http\Controllers;

use App\supplierModel;
use App\supplierTypeModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class supplierController extends Controller
{
    public function __construct()
    {
        $this->email = new emailController();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        try{
            $this->validate($request, [
                'name' => 'required|min:6',
                'address' => 'required|min:6',
                'email' => 'required|unique:suppliers|min:6|email',
                'password' => 'required|min:6',
                'confirmation_password' => 'required|same:password',
            ]);

            $data = new supplierModel();
            $data->name = $request->name;
            $data->address = $request->address;
            $data->email = $request->email;
            $data->password = bcrypt($request->password);
            $data->supplier_type = $request->supplier_type;
            $data->slogan = $request->slogan;
            $code = time();
            $data->supplier_code = $code;
            $data->save();
            //$this->email->registration($request->name,$request->email,$code);
            return redirect()->back()->with('response', 'Register berhasil! silahkan gunakan '. $code .' untuk login sebagai username, dan password yang sudah anda masukkan! Jika anda lupa anda dapat mengeceknya di email anda!');

        }
        catch (\Exception $e){
            return redirect('supplier-register')->with('response-error', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function profile()
    {
        try{
            $supplier = supplierModel::where('id',Session::get('supplier_id'))->first();
            $type = supplierTypeModel::all();
            $data['supplier'] = $supplier;
            $data['type'] = $type;
            //$this->email->registration($request->name,$request->email,$code);
            return view('backends.supplier.edit_profile')->with($data);

        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $this->validate($request, [
                'confirmation_password' => 'same:password',
            ]);

            $data = supplierModel::where('id',decrypt($id))->first();
            $data->name = $request->name;
            $data->slogan = $request->slogan;
            $data->email = $request->email;
            if(empty($request->password)){
                $data->password = $data->password;
            }
            else{
                $data->password = bcrypt($request->password);
            }
            $data->address = $request->address;
            $data->supplier_type = $data->supplier_type;
            $data->save();
            return redirect('supplier/product')->with('response','Sucessfull update data!');

        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function login(){
        try{
            return view('backends.login');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }

    public function logout(){
        try{
            Session::flush();
            return redirect('supplier/login')->with('response','Berhasil logout!');
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error',$e->getMessage());
        }
    }


    public function check_login(Request $request){
        try{
            $data = supplierModel::where('supplier_code',$request->code)->where('status',1)->first();

            if($data){
                if(Hash::check($request->password,$data->password)){
                    Session::put('supplier_id',$data->id);
                    Session::put('supplier_name',$data->name);
                    Session::put('supplier_email',$data->email);
                    Session::put('supplier_isLogin',true);
                    return redirect()->route('product.index');
                }
                else{
                    return redirect()->back()->with('response-error', 'Wrong credientials username or password!');
                }
            }
            else{
                return redirect()->back()->with('response-error', 'We can`t found this account');
            }
        }
        catch (\Exception $e){
            return redirect()->back()->with('response-error', $e->getMessage());
        }
    }


    public function register(){
        try{
            $data['supplier_type'] = supplierTypeModel::all();
            return view('backends.register')->with($data);
        }
        catch (\Exception $e){
            return redirect('supplier-register')->with('response-error', $e->getMessage());
        }

    }
}

resources/views/backends/supplier/product/add.blade.php
@extends('backends.base')
@section('content')
    <div id="page-wrapper">
        <div class="main-page">
            <div class="validation-section">
                <div class="col-md-12 validation-grid">
                    <h4>Add Product Form</h4>
                    <div class="validation-grid1">
                        <div class="valid-top">
                            @include('backends.alert')
                            <form id="defaultForm" method="post" class="form-horizontal" action="{{ route('product.store') }}">
                                {{csrf_field()}}
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Product Name</label>
                                    <div class="col-lg-5">
                                        <input type="text" class="form-control" name="name" placeholder="Product Name..."/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Product Code</label>
                                    <div class="col-lg-5">
                                        <input type="text" class="form-control" name="product_code" placeholder="Product Code... (Example: prod-15191219)"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Product Type</label>
                                    <div class="col-lg-5">
                                        <select class="form-control" name="product_type">
                                            <option selected="selected"> --- Product Type ---</option>
                                            @foreach($product_type as $item)
                                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Price</label>
                                    <div class="col-lg-5">
                                        <input type="text" class="form-control" name="price" placeholder="Product Price..."/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-9 col-lg-offset-3">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        </section>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection

resources/views/backends/supplier/product/edit.blade.php
@extends('backends.base')
@section('content')
    <div id="page-wrapper">
        <div class="main-page">
            <div class="validation-section">
                <div class="col-md-12 validation-grid">
                    <h4>Edit Product Form</h4>
                    <div class="validation-grid1">
                        <div class="valid-top">
                            @include('backends.alert')
                            <form id="defaultForm" method="post" class="form-horizontal" action="{{ route('product.update', encrypt($product->id)) }}">
                                {{csrf_field()}}
                                {{method_field('PUT')}}
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Product Name</label>
                                    <div class="col-lg-5">
                                        <input type="text" class="form-control" name="name" placeholder="Product Name..." value="{{ $product->name }}"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Product Code</label>
                                    <div class="col-lg-5">
                                        <input disabled type="text" class="form-control" name="product_code" placeholder="Product Code... (Example: prod-15191219)" value="{{ $product->product_code }}"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Product Type</label>
                                    <div class="col-lg-5">
                                        <select disabled class="form-control" name="product_type">
                                            <option selected="selected"> --- Product Type ---</option>
                                            @foreach($product_type as $type)
                                                <option @if($product->product_type == $type->id)selected = "selected" @endif value="{{ $type->id }}">{{ $type->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Price</label>
                                    <div class="col-lg-5">
                                        <input type="text" class="form-control" name="price" placeholder="Product Price..." value="{{ $product->price }}"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Product Status</label>
                                    <div class="col-lg-5">
                                        <select class="form-control" name="product_status">
                                            @if($product->status == 1)
                                                <option value="1">Active</option>
                                                <option value="0">Disabled</option>
                                            @else
                                                <option value="0">Disabled</option>
                                                <option value="1">Active</option>
                                            @endif
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-9 col-lg-offset-3">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        </section>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection

resources/views/backends/supplier/product/show.blade.php
@extends('backends.base')
@section('content')
    <div id="page-wrapper">
        <div class="main-page">
            <h2 class="hdg">Daftar Produk</h2>
            <div class="bottom-table">
                <div class="bs-docs-example">
                    @include('backends.alert')
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Product Code</th>
                            <th>Product Type</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php $no = 1 @endphp
                        @foreach($product as $item)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $item->product_code }}</td>
                            @foreach(\App\productTypeModel::where('id',$item->product_type)->get() as $value)
                            <td>{{ $value->name }}</td>
                            @endforeach
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->price }}</td>
                            <td>
                                @if($item->status == 1)
                                    Available
                                @else
                                    Not Available
                                @endif
                            </td>
                            <td>{{ $item->created_at }}</td>
                            <td><form method="post" action="{{ route('product.destroy',encrypt($item->id)) }}">
                                    {{csrf_field()}}
                                    {{method_field('DELETE')}}
                                    <a href="{{ route('product.edit',encrypt($item->id)) }}" class="btn btn-sm btn-primary">Edit</a>
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Are you sure?')">Delete</button>
                                </form></td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function(){
            $('.table').DataTable( {
                "pageLength": 5
            });
        });
    </script>
@endsection

resources/views/backends/supplier/product/type.blade.php
@extends('backends.base')
@section('content')
    <div id="page-wrapper">
        <div class="main-page">
            <h2 class="hdg">Product Type</h2>
            <div class="bottom-table">
                <div class="bs-docs-example">
                    @include('backends.alert')
                    <table class="table table-hover table-bordered">
                        <tbody>
                        @php $no = 1 @endphp
                        @foreach($product_type as $item)
                        <tr>
                            <td><center><a href="{{ route('product.show',encrypt($item->id)) }}"><font size="6">{{ $item->name }}</font></a> </center></td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection